cc_binary(
	name = "firework",
	srcs = ["firework.c"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)

cc_binary(
	name = "ozdemo",
	srcs = ["ozdemo.c"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)

cc_binary(
	name = "ptest",
	srcs = ["ptest.c"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)

cc_binary(
	name = "rain",
	srcs = ["rain.c"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)

cc_binary(
	name = "testcurs",
	srcs = ["testcurs.c"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)

cc_binary(
	name = "tuidemo",
	srcs = ["tuidemo.c", "tui.c", "tui.h"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)

cc_binary(
	name = "worm",
	srcs = ["worm.c"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)

cc_binary(
	name = "xmas",
	srcs = ["xmas.c"],
	deps = ["//:PDCurses"],
	tags = ["demo"],
)
